{% set name = "GACODE" %}
{% set version = "0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  skip: True [py3k]

requirements:
  run:
    - conda-build
    - fann2
    - fftw
    - gfortran_osx-64  # [osx]
    - libgfortran
    - libnetcdf
    - matplotlib
    - mpich
    - netcdf-fortran
    - numpy
    - python

about:
  home: http://github.com/gafusion/gacode
  # Remember to specify the license variants for BSD, Apache, GPL, and LGLP.
  # Prefer the short version, e.g: GPL-2.0 instead of GNU General Public License version 2.0
  # See https://opensource.org/licenses/alphabetical
#  license: MIT
  # The license_family, i.e. "BSD" if license is "BSD-3-Clause". (optional)
#  license_family: MIT
  # It is strongly encouraged to include a license file in the package,
  # (even if the license doesn't require it) using the license_file entry.
  # See http://conda.pydata.org/docs/building/meta-yaml.html#license-file
#  license_file: LICENSE.rst
#  summary: 'Simple, fast, extensible JSON encoder/decoder for Python'

  # The remaining entries in this section are optional, but recommended
  description: |
    GACODE contains the transport solver, TGYRO, the turbulence transport model, TGLF,
    the neoclassical model, NEO, and the gyrokinetic models, CGYRO and GYRO.  
  doc_url: http://gafusion.github.io/OMFIT-source
  dev_url: https://github.com/gafusion/OMFIT-source

extra:
  recipe-maintainers:
    - smithsp
